### PR TITLE
Added more content after rereading the rules.

### PR DESCRIPTION
**Pull request by ledewitt**
I reread the rules while waiting for my kids at school, came home and hammered out some more things on the to do list.

One thing of note is that there are events which can cause players to lose control of buildings and for them to become uncontrolled or neutral on the board.

Another thing I need to look for is what kind of object is the DOM and JS using that I can store the player state in?  I need to keep a tally on their score and color plus some kind of link to the buildings they own so victory points can be tracked as things happen.

### CODE REVIEW

**Comment by ledewitt** [comment]
Specifically what I am asking is for something, a keyword, I can search on which will show me how to keep local variables in something like a hash in the DOM.

**Comment by JEG2** [comment]
```JavaScript
var game_state = { };

function whatever() {
  // ... use game_state ...
}
```

**Comment by tnordloh** [comment]
I'm making the prestige/wealth markers now; once I have them, I might need that game_state, to actually implement placing the markers.  If you haven't created the game_state by then, I'll put it in there.

I'll. likely make something like this:
```javascript
//This is essentially pseudocode; I don't know javascript syntax that well
var game_state = {
  "player_state": {
    //player names, elected offices, and whatnot, here.
  }
  "board_state": { 
     //token locations here
 }
}
```

**Comment by ledewitt** [comment]
So what I am thinking is that a building has to know what player owns it or
no player owns it.  Rows have to know how to iterate over all the buildings
in those rows for checking scores.  And a player object has to have a
function to be able to sweep over the board to look find all the buildings
belonging to that player.  Or maybe the a general function is responsible
for iterating over the players to find the one with the most valuable type
of building.  This is just me rambling:

Simply to start I will create a way to create a player that contains the
name of the player and the their color.  I am super busy this weekend with
out of town visitors but that small amount is the first toe hold I am going
to try and get a carabiner into.

——

Luke DeWitt: luke@dewittsoft.com
DeWitt Software, LLC
Cell: 303 941 2141

**Comment by ledewitt** [comment]
If I delete this branch will I be able to get back to your comments about the game_state hash?

**Comment by JEG2** [comment]
Yes.  The PR discussion stays.

**Pull request merged**
